import type { Incident } from "./types";

/**
 * Five incident scenarios, escalating in difficulty.
 * Every one is drawn from real-world engineering scenarios.
 */
export const INCIDENTS: Incident[] = [
  /* ─── 1 · Silent deploy ─────────────────────────────── */
  {
    id: "silent-deploy",
    title: "web-app deploy green, users see stale build",
    service: "web-app · production",
    context: "Deploy pipeline reported success 22 minutes ago. Users are still seeing the previous build's bundle hash in the wild.",
    seconds: 90,
    difficulty: "P3",
    evidence: [
      {
        id: "chart-deploy",
        kind: "chart",
        label: "Deploy events / min",
        detail: "A deploy event fired at 14:03. No further deploys since. The graph shows exactly one spike at 14:03 and nothing after.",
        weight: 1,
        series: [0.1, 0.1, 0.9, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        anomaly: "spike",
        cluster: "deploy",
      },
      {
        id: "chart-cdn",
        kind: "chart",
        label: "CDN 4xx / min",
        detail: "CDN 4xx rate is flat. Nothing exotic in cache errors.",
        weight: 0,
        series: [0.15, 0.12, 0.14, 0.13, 0.12, 0.14, 0.13, 0.14, 0.12, 0.13],
        anomaly: "normal",
      },
      {
        id: "chart-latency",
        kind: "chart",
        label: "Origin p95 latency",
        detail: "Server p95 latency is boring flat. No performance regression, no cold start.",
        weight: 0,
        series: [0.3, 0.32, 0.3, 0.31, 0.3, 0.3, 0.31, 0.3, 0.3, 0.3],
        anomaly: "normal",
      },
      {
        id: "chart-index-hash",
        kind: "chart",
        label: "index.html bundle hash",
        detail: "The hash in the served index.html has NOT changed since 12:00. Deploy claimed to publish new hash a7c9f1 at 14:03; served hash is still 3b0eaa.",
        weight: 2,
        series: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
        anomaly: "flatline",
        cluster: "deploy",
      },
      {
        id: "log-cdn-purge",
        kind: "log",
        label: "cdn.purge failed silently",
        detail: "'cdn.purge webapp/index.html' returned 200 with body { \"queued\": true } - but the queue was drained without executing (rate-limited by CDN provider, no retry).",
        weight: 2,
        ts: "14:03",
        cluster: "deploy",
      },
      {
        id: "log-migration",
        kind: "log",
        label: "npm install ok",
        detail: "Deploy runner: 'npm ci' completed in 34s. Nothing unusual.",
        weight: 0,
        ts: "14:00",
      },
      {
        id: "pr-new-header",
        kind: "pr",
        label: "Add Cache-Control override",
        detail: "PR that ships the new build. Adds a Cache-Control: no-store header on index.html, unrelated to the CDN purge path.",
        weight: -1,
        pr: { title: "Add Cache-Control override on index.html", author: "@amrit", branch: "cache-control-index", number: 4318 },
        cluster: "deploy",
      },
      {
        id: "alert-noise",
        kind: "alert",
        label: "cost spike alert",
        detail: "Unrelated billing anomaly on the analytics side account.",
        weight: 0,
      },
    ],
    hypotheses: [
      {
        id: "cdn-purge",
        label: "CDN purge silently failed after successful deploy",
        fix: "Add a post-purge verification step that re-fetches index.html and compares the served bundle hash to the deployed hash. Fail the pipeline if they don't match.",
        correct: true,
        postmortem: "The CDN provider's purge queue was rate-limited. The API returned 200 with { queued: true } but never actually drained. Users kept getting the old bundle from the edge. Verification-after-deploy would have caught this in < 2 minutes.",
      },
      {
        id: "bad-cache-header",
        label: "Cache-Control override caused stale caching",
        fix: "Revert PR #4318 and add explicit no-store for the HTML entry point.",
        correct: false,
        postmortem: "The Cache-Control PR is a red herring - no-store would have prevented staleness, not caused it. And 22 minutes of staleness against a 5-minute TTL is way too long to be a Cache-Control issue.",
      },
      {
        id: "npm-cache",
        label: "npm cache poisoned during install",
        fix: "Clear the CI runner's global npm cache; pin to a known-good lockfile.",
        correct: false,
        postmortem: "The install step succeeded and produced the correct new bundle hash. The build artifact is fine. The problem is downstream of the build.",
      },
      {
        id: "origin-slow",
        label: "Origin server is under-provisioned",
        fix: "Scale up the origin fleet.",
        correct: false,
        postmortem: "Origin p95 is boring flat. Latency isn't the story here - bundle staleness is.",
      },
    ],
  },

  /* ─── 2 · Flakiness spike after auth migration ──────── */
  {
    id: "flake-spike",
    title: "e2e flakiness spike after auth migration",
    service: "e2e · main",
    context: "You just rolled out the the new secrets vault migration. Overnight, e2e failure rate went from 4% to 41% on main. Was it the auth change? Or the parallel the new browser version upgrade?",
    seconds: 100,
    difficulty: "P2",
    evidence: [
      {
        id: "chart-failure-rate",
        kind: "chart",
        label: "e2e failure %",
        detail: "Steady 4% for two weeks. Then a step-function jump to 41% at 03:12 UTC.",
        weight: 1,
        series: [0.1, 0.1, 0.1, 0.1, 0.1, 0.85, 0.83, 0.86, 0.84, 0.85],
        anomaly: "spike",
        cluster: "auth",
      },
      {
        id: "chart-per-shard",
        kind: "chart",
        label: "failure % by shard",
        detail: "The 41% is not uniform. Shards 1, 2, 3 (Browser A) are at 68%. Shards 4, 5, 6 (Browser B) are still at 4%. Failure is lane-specific.",
        weight: 2,
        series: [0.1, 0.15, 0.12, 0.68, 0.68, 0.65, 0.7, 0.68, 0.66, 0.67],
        anomaly: "spike",
        cluster: "browser",
      },
      {
        id: "chart-auth-latency",
        kind: "chart",
        label: "secrets fetch p95",
        detail: "Auth fetch latency is completely flat at 12ms. Migration is behaving.",
        weight: -1,
        series: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15],
        anomaly: "normal",
        cluster: "auth",
      },
      {
        id: "chart-video-size",
        kind: "chart",
        label: "test video size avg",
        detail: "Video artifact size unchanged. Not a browser test output issue.",
        weight: 0,
        series: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4],
        anomaly: "normal",
      },
      {
        id: "log-chrome-upgrade",
        kind: "log",
        label: "Browser vendor bumped a minor version",
        detail: "the browser test image bumped the browser version 137 → 138 at 03:11 UTC - one minute before the failure spike began.",
        weight: 2,
        ts: "03:11",
        cluster: "browser",
      },
      {
        id: "log-auth-rotation",
        kind: "log",
        label: "auth token rotated OK",
        detail: "The vault rotated the CI token at 02:00 UTC. Rotation completed cleanly. All post-rotation requests succeeded.",
        weight: -1,
        ts: "02:00",
        cluster: "auth",
      },
      {
        id: "log-timeout-pattern",
        kind: "log",
        label: "TimeoutError: waiting for selector",
        detail: "Failing tests are all failing on 'waitForSelector' timing in the modal flow. The selector matches, but the new browser version changed the click event timing on shadow-DOM boundaries.",
        weight: 2,
        ts: "03:14",
        cluster: "browser",
      },
      {
        id: "pr-auth",
        kind: "pr",
        label: "Migrate to the new secrets vault",
        detail: "The auth migration PR. Ships new fetch client + rotation hook. Merged 8 hours before the spike.",
        weight: -1,
        pr: { title: "Migrate package auth to the new secrets vault", author: "@you", branch: "auth-secrets-mgr", number: 4204 },
        cluster: "auth",
      },
      {
        id: "alert-page",
        kind: "alert",
        label: "PagerDuty: e2e failure rate > 30%",
        detail: "The alert that woke you up.",
        weight: 0,
      },
    ],
    hypotheses: [
      {
        id: "chrome-138",
        label: "the new browser version upgrade changed shadow-DOM click timing",
        fix: "Pin the browser to the previous minor for e2e until the shadow-DOM selectors are updated to use user-facing role queries instead of DOM traversal.",
        correct: true,
        postmortem: "the new browser version shipped a change to click-event dispatch through shadow roots. the browser test runner's default click handler now needs a small settle time on modals that live inside web components. Browser B was unaffected. The auth migration is a coincidence - its timing put it in the blast radius, not the cause.",
      },
      {
        id: "auth-migration",
        label: "secrets-vault migration broke auth",
        fix: "Roll back PR #4204 and revert to hardcoded tokens.",
        correct: false,
        postmortem: "The auth fetch is flat and green. Rotation succeeded. Browser B shards use the same auth path and are at 4%. It's not auth.",
      },
      {
        id: "flake-in-test",
        label: "New flaky test landed in main",
        fix: "Run the flakiness detection sweep against the last 24h of commits.",
        correct: false,
        postmortem: "A single flaky test would not step-function 3 shards from 10% to 68% at exactly the same timestamp. The synchronicity across shards is the tell.",
      },
      {
        id: "network-issue",
        label: "Cloud region network blip",
        fix: "Wait it out; escalate to infra if it persists.",
        correct: false,
        postmortem: "A network blip would produce diffuse timeouts across all lanes, not a lane-specific click-timing pattern.",
      },
    ],
  },

  /* ─── 3 · Route attribution drift ───────────────────── */
  {
    id: "route-drift",
    title: "route attribution wrong on the customer dashboard",
    service: "dashboard-app · production",
    context: "Analytics dashboards are misattributing hits after a small routing PR. /invoices?tab=paid&sort=asc is being counted as /invoices?sort=asc&tab=paid - same route, but the string comparison thinks they're different.",
    seconds: 90,
    difficulty: "P2",
    evidence: [
      {
        id: "chart-unmatched",
        kind: "chart",
        label: "'unmatched route' events",
        detail: "The 'unmatched route' counter - which usually sits near zero - spiked to 22K/min at 09:47.",
        weight: 2,
        series: [0.05, 0.05, 0.05, 0.05, 0.05, 0.85, 0.9, 0.88, 0.87, 0.88],
        anomaly: "spike",
        cluster: "attribution",
      },
      {
        id: "chart-traffic",
        kind: "chart",
        label: "total requests / min",
        detail: "Overall traffic to dashboard-app is unchanged. Only the attribution is wrong.",
        weight: 1,
        series: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        anomaly: "normal",
        cluster: "attribution",
      },
      {
        id: "chart-error-rate",
        kind: "chart",
        label: "5xx rate",
        detail: "Server errors are flat. This is a metrics problem, not a serving problem.",
        weight: 0,
        series: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        anomaly: "normal",
      },
      {
        id: "log-drift-hit",
        kind: "log",
        label: "route hit but no match",
        detail: "'incoming: /invoices?sort=asc&tab=paid | matched: (none)' - hundreds per second. Same URL, different param order.",
        weight: 2,
        ts: "09:47",
        cluster: "attribution",
      },
      {
        id: "log-fe-change",
        kind: "log",
        label: "browser URL rewrite",
        detail: "The Next.js router now normalises query params alphabetically. Every URL is being re-emitted in a canonical order.",
        weight: 2,
        ts: "09:45",
        cluster: "attribution",
      },
      {
        id: "log-service-restart",
        kind: "log",
        label: "attribution restart",
        detail: "attribution service was rolling-restarted at 09:30 (unrelated deploy).",
        weight: -1,
        ts: "09:30",
      },
      {
        id: "pr-next-upgrade",
        kind: "pr",
        label: "Next.js 14.1 → 14.2 upgrade",
        detail: "Bumps Next.js minor version. Release notes mention router internals but do not call out query param ordering.",
        weight: 2,
        pr: { title: "Bump Next.js 14.1 → 14.2 (router internals)", author: "@akshay", branch: "next-14-2", number: 4290 },
        cluster: "attribution",
      },
      {
        id: "pr-analytics",
        kind: "pr",
        label: "Rename analytics event names",
        detail: "Cosmetic rename in event constants, no attribution matcher change.",
        weight: 0,
        pr: { title: "Rename analytics events for clarity", author: "@amrit", branch: "analytics-rename", number: 4285 },
      },
      {
        id: "alert-noise",
        kind: "alert",
        label: "attribution volume delta > 40%",
        detail: "The alert that fired at 09:47.",
        weight: 0,
      },
    ],
    hypotheses: [
      {
        id: "string-match",
        label: "Attribution matcher uses string compare; canonical param ordering broke it",
        fix: "Rewrite the matcher to parse into an object and compare property sets - order-independent and extra-param tolerant. Add a compatibility layer for the old shape.",
        correct: true,
        postmortem: "Next.js 14.2 quietly canonicalised query params. The attribution matcher was doing raw string equality on the URL. Alphabetising the params changed the string and broke every match. This is exactly the redesign that shipped later - object-based query comparison, order-independent, backward-compatible.",
      },
      {
        id: "svc-restart",
        label: "attribution restart lost in-memory route table",
        fix: "Persist the route table to disk and reload on boot.",
        correct: false,
        postmortem: "The service is running fine and emitting the 'no match' log line - meaning it's receiving requests and running the matcher. The matcher is the problem, not the presence of the service.",
      },
      {
        id: "analytics-rename",
        label: "Analytics event rename broke downstream",
        fix: "Revert PR #4285.",
        correct: false,
        postmortem: "The rename was cosmetic. The matcher key hasn't changed. Attribution volume is spiking on 'no match', not on missing event names.",
      },
      {
        id: "traffic-anomaly",
        label: "New traffic pattern from a client update",
        fix: "Rate-limit the offending client fleet.",
        correct: false,
        postmortem: "Total traffic is flat. This is not new traffic, it's the same traffic being mis-labeled.",
      },
    ],
  },

  /* ─── 4 · The 3am page ──────────────────────────────── */
  {
    id: "weekly-3am",
    title: "on-call analytics job dies every Sunday 3am",
    service: "analytics-etl · schedule",
    context: "The weekly analytics ETL job you built has died three Sundays in a row at exactly 03:00 UTC. CI pipeline hangs. chat post never appears. Nobody notices until Monday.",
    seconds: 100,
    difficulty: "P2",
    evidence: [
      {
        id: "chart-runtime",
        kind: "chart",
        label: "job runtime / week",
        detail: "Job normally completes in 6 minutes. The last three Sundays it ran for 25 minutes and then CI auto-killed it.",
        weight: 1,
        series: [0.15, 0.15, 0.15, 0.15, 0.9, 0.9, 0.9],
        anomaly: "creep",
        cluster: "runtime",
      },
      {
        id: "chart-slack-quota",
        kind: "chart",
        label: "the chat API rate limit hits",
        detail: "the chat API quota headroom is completely fine. No rate limiting at any hour.",
        weight: 0,
        series: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
        anomaly: "normal",
      },
      {
        id: "chart-buildkite-agents",
        kind: "chart",
        label: "CI runner availability",
        detail: "Agents are plentiful at 03:00 UTC. Not a scheduling starvation issue.",
        weight: 0,
        series: [0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9],
        anomaly: "normal",
      },
      {
        id: "chart-timezone-users",
        kind: "chart",
        label: "reporting timezone diversity",
        detail: "The job queries users across every timezone. TTFR-by-timezone is one of its outputs.",
        weight: 1,
        anomaly: "normal",
        series: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
        cluster: "timezone",
      },
      {
        id: "log-hang",
        kind: "log",
        label: "job hung on 'window boundary compute'",
        detail: "Last log line before hang: 'Computing week boundary for user tz=America/Los_Angeles'. Then nothing for 25 minutes until CI kills it.",
        weight: 2,
        ts: "03:00",
        cluster: "timezone",
      },
      {
        id: "log-dst",
        kind: "log",
        label: "DST transition today",
        detail: "System timezone DB notes that DST ended in America/Los_Angeles at 02:00 local (yesterday's midnight UTC-8), producing a 25-hour Sunday in PT.",
        weight: 2,
        ts: "02:00",
        cluster: "timezone",
      },
      {
        id: "log-slack-post",
        kind: "log",
        label: "chat post never attempted",
        detail: "The post-to-chat step is the final one. It never runs because the job hangs upstream.",
        weight: -1,
        ts: "N/A",
      },
      {
        id: "pr-etl",
        kind: "pr",
        label: "Stateless ETL: week window compute",
        detail: "The original PR that shipped the ETL. Computes week boundaries as 'start = end - 7*24h' - assumes 168-hour weeks.",
        weight: 2,
        pr: { title: "Weekly analytics ETL (stateless)", author: "@you", branch: "analytics-etl", number: 3812 },
        cluster: "timezone",
      },
      {
        id: "alert-timeout",
        kind: "alert",
        label: "CI: pipeline killed (timeout)",
        detail: "The alert that fires every Sunday.",
        weight: 0,
      },
    ],
    hypotheses: [
      {
        id: "dst",
        label: "DST transition produces a non-168h week; window compute loops",
        fix: "Replace fixed 7*24h with a proper timezone-aware week boundary (Luxon Duration.fromObject({ weeks: 1 })). Add tests around DST fall-back and spring-forward.",
        correct: true,
        postmortem: "DST fall-back gives US timezones a 25-hour Sunday. The ETL's window loop increments by exactly 24h until it hits the end - but with a 25h day, it never lines up with the anchor, so it loops. The Sundays it died were all US DST transition weekends. Timezone-aware duration math fixes it.",
      },
      {
        id: "slack-quota",
        label: "the chat API rate-limits weekly bursts",
        fix: "Batch chat posts with backoff.",
        correct: false,
        postmortem: "chat API quota is nowhere near the limit and the chat step never even ran. It hangs earlier.",
      },
      {
        id: "buildkite-scheduling",
        label: "CI scheduler starves the job at 3am",
        fix: "Reserve a dedicated agent for the ETL.",
        correct: false,
        postmortem: "Agents are plentiful at 03:00 UTC. The job starts on time; it just doesn't finish.",
      },
      {
        id: "stateful-db",
        label: "Stateless ETL needs a checkpoint DB",
        fix: "Add a persistent state store.",
        correct: false,
        postmortem: "Statefulness would help resumability, not the underlying compute bug. The hang is deterministic, not a resume issue.",
      },
    ],
  },

  /* ─── 5 · Phased rollout stuck ──────────────────────── */
  {
    id: "stuck-rollout",
    title: "Secrets vault phased rollout stuck at 20%",
    service: "package-auth · phased rollout",
    context: "The phased secrets-vault rollout is stuck at 20% for the last four hours. The health check keeps flapping between OK and DEGRADED. No auto-promotion, no auto-rollback. Just… frozen.",
    seconds: 110,
    difficulty: "P1",
    evidence: [
      {
        id: "chart-progress",
        kind: "chart",
        label: "rollout %",
        detail: "0% → 20% in the first 10 minutes. Then absolutely flat for four hours.",
        weight: 1,
        series: [0, 0.05, 0.1, 0.15, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
        anomaly: "flatline",
        cluster: "rollout",
      },
      {
        id: "chart-health",
        kind: "chart",
        label: "health check pass rate",
        detail: "Health checks oscillate: 98% pass, then 91%, then 98%, then 89%. Bouncing across the promotion threshold (95%).",
        weight: 2,
        series: [0.98, 0.91, 0.98, 0.89, 0.97, 0.9, 0.96, 0.88, 0.98, 0.91],
        anomaly: "spike",
        cluster: "health",
      },
      {
        id: "chart-auth-latency",
        kind: "chart",
        label: "auth p95 latency",
        detail: "Latency is boring flat at 12ms. Not a performance problem.",
        weight: 0,
        series: [0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15, 0.15],
        anomaly: "normal",
      },
      {
        id: "chart-package-cache",
        kind: "chart",
        label: "package cache hit rate",
        detail: "Cache hits are near-perfect. Every install is hitting the local cache.",
        weight: -1,
        series: [0.95, 0.94, 0.95, 0.95, 0.94, 0.95, 0.94, 0.95, 0.95, 0.94],
        anomaly: "normal",
        cluster: "cache",
      },
      {
        id: "log-check-failing",
        kind: "log",
        label: "health check timeout on 5% of nodes",
        detail: "The failing 5-10% of nodes are all first-time-through - their local package cache is cold. The health check hits the auth endpoint AND does a real 'npm view'; the latter times out on cold caches.",
        weight: 2,
        ts: "hourly",
        cluster: "health",
      },
      {
        id: "log-old-nodes",
        kind: "log",
        label: "healthy nodes stay healthy",
        detail: "The nodes that passed once continue to pass. Warm caches make the health check pass consistently.",
        weight: 2,
        ts: "hourly",
        cluster: "health",
      },
      {
        id: "log-rotation",
        kind: "log",
        label: "credential rotation succeeded",
        detail: "vault rotation happened cleanly 6 hours ago.",
        weight: -1,
        ts: "06h ago",
      },
      {
        id: "pr-healthcheck",
        kind: "pr",
        label: "Beef up health check",
        detail: "PR that made the health check 'more thorough' by adding a real 'npm view' step, on top of the simple auth-endpoint ping.",
        weight: 2,
        pr: { title: "Health check: add real npm view", author: "@rohit", branch: "healthcheck-thorough", number: 4340 },
        cluster: "health",
      },
      {
        id: "pr-rollout-tool",
        kind: "pr",
        label: "Phased rollout tool v2",
        detail: "The rollout tool itself. Auto-promotes at 95% health, auto-rolls back at < 90%. No changes recently.",
        weight: 0,
        pr: { title: "Phased rollout controller v2", author: "@you", branch: "rollout-v2", number: 3980 },
      },
      {
        id: "alert-flap",
        kind: "alert",
        label: "rollout controller: health flapping",
        detail: "The alert has fired every 20 minutes for 4 hours. Nobody is listening.",
        weight: 0,
      },
    ],
    hypotheses: [
      {
        id: "healthcheck-cold-cache",
        label: "Health check is testing cold-cache behavior; oscillates around promotion threshold",
        fix: "Warm the package cache before the health check runs, or split the check into two: 'auth works' (fast, high threshold) and 'npm end-to-end works' (slow, sampled). Promote on the fast check; monitor the slow one asynchronously.",
        correct: true,
        postmortem: "The 'more thorough' health check added a real 'npm view' call, which is cheap on warm caches and slow-to-timeout on cold ones. New nodes have cold caches, fail the check, get de-registered - but then the fleet shrinks and the health % oscillates around 95%. The rollout controller sees the flap and refuses to promote or roll back. Splitting the check fixes it.",
      },
      {
        id: "secrets-rotation",
        label: "vault rotation half-applied",
        fix: "Force a full rotation with pinned credentials.",
        correct: false,
        postmortem: "Rotation completed cleanly 6 hours ago and auth latency is flat. Auth is fine; the health check is the flapper.",
      },
      {
        id: "rollout-tool-bug",
        label: "Rollout tool has a threshold bug",
        fix: "Revert PR #3980, redeploy from a known-good tag.",
        correct: false,
        postmortem: "The rollout tool hasn't changed. It's correctly seeing the flap and correctly refusing to promote. The signal it's reading is the problem.",
      },
      {
        id: "cache-poisoning",
        label: "Package cache is poisoned",
        fix: "Purge and rebuild the shared package cache.",
        correct: false,
        postmortem: "Cache hit rate is 95%. Cache is healthy; it's the newness of specific node caches that trips the health check.",
      },
    ],
  },
];
